#!/bin/csh -f
foreach m (UNUSED NEW OFFLINE DEADLOCKED LOCKING LOCKED UNLOCKING UNLOCKED OPEN CLOSED LOCKING PROPPED PROPPEDOK AJAR FAULT TAMPER FORCED)
	/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD -o ../door$m.png -D 'mode="'$m'"' --imgsize=1000,1830 --render --camera=544,98,906,68,0,354,5600 Door.scad
end
