M48
; DRILL file {KiCad (6.0.5-0)} date Monday, 15 August 2022 at 15:55:02
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-15T15:55:02+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0315
%
G90
G05
T1
X5.675Y-3.1441
X5.675Y-3.3717
T2
X5.4646Y-3.4311
X5.4646Y-3.5098
T0
M30
